### PR TITLE
Adapt download file name and export as SVG and PNG

### PR DESCRIPTION
**Pull request by SharonNaemi**
#### Short Description
Currently, the only posssible export of a workflow model was bpmn. The system does not provide a direct export feature for PNG and SVG files. Instead, users are required to manually export the workflow diagrams themselves by taking screenshots or using third-party tools capable of converting BPMN files to PNG or SVG formats.

#### Proposed Changes

  * adapt the ui for the save button so that the user can configure the file format
  * enable to change the file name
  * enable the export as svg and png

### CODE REVIEW

**Comment by SharonNaemi** [comment]
> Is it possible to open the file dialog when saving the files to directly select the name and location? Currently, only the file name is configurable and not the path. Furthermore, it would be nice to directly use the 3 buttons (similar to the plugin buttons) to save the file instead of first selecting the checkbox and then clicking on the general save button.

I will look if I can integrate the file dialog when saving the file.  Regarding the checkbox: Should I remove them and add instead the dropdown in the config dialog or keep the checkbox + add dropdown ?

**Comment by wederbn** [comment]
I would suggest adding 4 buttons: 3 for the single formats and one save all button. Or do you have a use case which requires saving 2 out of the 3 formats?

**Comment by SharonNaemi** [comment]
> I would suggest adding 4 buttons: 3 for the single formats and one save all button. Or do you have a use case which requires saving 2 out of the 3 formats?

Okay, I will remove then the checkbox and add these options to the config. Small update: found a way to open the file dialog:)

**Review by mbeisel — CHANGES_REQUESTED** [review]
feedback commented above :)

**Comment by SharonNaemi** [comment]
> * It would be great if the location of an opened file would be remembered for saving.
>   Default location when starting the modeler: downloads
>   Set location to downloads when clicking on new file
>   Set location to folder a/b/c when opening a/b/c/file.bpmn
>   Is that possible?
No, it is not possible. The selected directory cannot be accessed.

**Review by mbeisel — APPROVED** [review]

**Pull request merged**
