### PR TITLE
enable to resize properties panel

### PR DESCRIPTION
**Pull request by SharonNaemi**
#### Short Description
Currently, the size of the properties panel cannot be changed.

#### Proposed Changes

  * enable to increase and reduce the size of the properties panel by adding two resize buttons

### CODE REVIEW

**Review by mbeisel — CHANGES_REQUESTED** [review]
Functionalitiy works as intended :)

However, to improve the intuitivity of the + and - button they should be somehow attached to the properties panel (maybe make them visible when hovering the property panel or in case its not visible the right side of the modeler)
I'd suggest to check out the adaptability of the properties panel in the old modeler and implement it in a similar manner

**Comment by LaviniaStiliadou** [comment]
> Functionalitiy works as intended :)
> 
> However, to improve the intuitivity of the + and - button they should be somehow attached to the properties panel (maybe make them visible when hovering the property panel or in case its not visible the right side of the modeler) I'd suggest to check out the adaptability of the properties panel in the old modeler and implement it in a similar manner

I removed the resize buttons from the toolbar and added a collapse button instead (since we don't really need to make the properties panel bigger).

**Comment by wederbn** [comment]
When reducing the properties panel size to zero, it disappears and I`m unable to increase the size again. Maybe the collapse button can then be used to set the size to the default size of the properties panel again?

**Review by mbeisel — CHANGES_REQUESTED** [review]
Looks nice and works as intended, however, when clicking on the horizontal resize and slightly moving the mouse before starting to actually drag the properties panel container, the size of the properties panel is reduced by a certain percentage (around 20%).

**Review by wederbn — APPROVED** [review]
LGTM

**Pull request merged**
