### PR TITLE
Fix icons of data objects

### PR DESCRIPTION
**Pull request by LaviniaStiliadou**
Should fix issue #77.

### CODE REVIEW

**Comment by wederbn** [comment]
For testing purposes the following URL should be set as environment variable: DATA_CONFIG=https://raw.githubusercontent.com/PlanQK/workflow-modeler/fix/data-object-icons/components/bpmn-q/modeler-component/extensions/quantme/configurations/quantmeDataObjects.json

**Review by mbeisel — CHANGES_REQUESTED** [review]
DataObject Properties and Icons are missing. I assume that the custom dataobjects are not actually loaded.

**Review by wederbn — APPROVED** [review]
LGTM

**Review by mbeisel — APPROVED** [review]
Nice work by Lavinia and Benjamin

**Pull request merged**
