### PR TITLE
Implement subprocess expansion if deployment model is too big

### PR DESCRIPTION
**Pull request by wiomoc**
ref: #31

### CODE REVIEW

**Comment by LaviniaStiliadou** [comment]
Seems not to work for me. 
Subprocess

If I reload the topology, the edges are there but the subprocess is not expanded
Subprocess2

**Comment by KuhnMn** [comment]
I added a small improvement for the Smart Edges here. I noticed that the sorting by y only meant that edges coming from or going to the bottom or top still overlapped a lot, the example topology I had was barely decipherable, so I adjusted it. Might be better to move this to a different PR though or remove it if unwanted.

**Comment by wederbn** [comment]
Expanding the deployment model looks good in general, however, the margins are a bit too large:

image

Collapsing the deployment models leaves the subprocesses in the state with the expanded size.

**Comment by LaviniaStiliadou** [comment]
I think the margins are not right when explanding the deployment model. The topology nodes are outside the subprocess
topology-outside-subprocess

**Comment by LaviniaStiliadou** [comment]
no-csar
If the option: "No CSAR" is selected, the size of the subprocess does not change back.

**Comment by wederbn** [comment]
Closed, as the edges are currently not smart enough and lead to overlaps

**Pull request closed without merging**
